### ISSUE TITLE
Typo in ``xrdb merge <path to xresources file>`

### ISSUE THREAD

**Issue by dqkqd** [catppuccin/xresources#4]
According to https://wiki.archlinux.org/title/x_resources#Load_resource_file. I think it should be `xrdb -merge`

**Comment by dqkqd** [comment]
There is also another typo in `README.md`:
 https://github.com/catppuccin/xresources/blob/a9cd582faeef2f7410eb7d4b5a83d026e3f2b865/README.md?plain=1#L45
which should be `:` instead of `;`.

**Comment by nekowinston** [comment]
Good catch, thanks! I'll update it.
