### ISSUE TITLE
unexpected colors in xterm (compared with kitty)

### ISSUE THREAD

**Issue by asdf8601** [catppuccin/xresources#6]
On the left is kitty and xterm on the right. As you can see the colors aren't the same

![](https://i.imgur.com/eYtawe0.png)

macha.resources

```
*background: #1E1E2E
*foreground: #CDD6F4

! black
*color0: #45475A
*color8: #585B70

! red
*color1: #F38BA8
*color9: #F38BA8

! green
*color2: #A6E3A1
*color10: #A6E3A1

! yellow
*color3: #F9E2AF
*color11: #F9E2AF

! blue
*color4: #89B4FA
*color12: #89B4FA

! magenta
*color5: #F5C2E7
*color13: #F5C2E7

! cyan
*color6: #94E2D5
*color14: #94E2D5

! white
*color7: #BAC2DE
*color15: #A6ADC8
```

is this the expected behaviour?

**Comment by nekowinston** [comment]
Hey there :wave:

The colour definitions are the same across both configs, I've just checked it to make sure.

What's the output of your `echo $TERM`?
IIRC you might have to set `TERM=xterm-256color`

**Comment by asdf8601** [comment]
> IIRC you might have to set TERM=xterm-256color

Exactly!

**Comment by nekowinston** [comment]
Did that resolve your issue? Please close the issue if it did 🙂

**Comment by asdf8601** [comment]
ah no, sorry, I meant that your guess was right. 

To be clear, this is the output of `$TERM`:

```bash
$ echo $TERM
xterm-256color
```

**Comment by nekowinston** [comment]
Ah, alright, thanks for the clarification.

Currently not near a Linux machine, I'll try to check this out later – since the definitions are correct, I'm guessing there has to be some setting that fixes this.

**Comment by asdf8601** [comment]
awesome, thank you for your time  ;-) I love your work on this theme, guys!

**Comment by nekowinston** [comment]
@mmngreco sadly I can't reproduce this issue - it seems to correctly set the colors for me. My Xresources config is the same as `mocha.resources`, with these additions:

```
XTerm.termName: xterm-256color
XTerm.vt100.locale: false
XTerm.vt100.utf8: true
XTerm.vt100.backarrowKey: false
XTerm.ttyModes: erase ^?
```

**Comment by asdf8601** [comment]
@nekowinston thank you for your answer. I've used your config but it didn't fix the issue 

![image](https://user-images.githubusercontent.com/6231413/201297715-b651e0c3-6e85-43f5-9998-52360bf2021f.png)

I'm using zsh on Pop!_os and i3 in case this may helps. 

Any idea if there's another variable that may cause this ? I've checked my `.profile` , `.bashrc`, `.bash_profile`, `.zshrc` and I didn't find anything.

**Comment by asdf8601** [comment]
I was checking this more in details and I think that the problem is on kitty but xterm. I thought that the right color were those from kitty because I've started using there in the first time but aren't (I think).

Closing this and thanks for your support @nekowinston  ;-)
